step 10 - Page Object Model
Juansereina/protractor-workshop-2019 pull request #10
Opened 2019-01-23 03:18 UTC by Juansereina

2019-01-25 19:39 UTC, aperdomob requested changes

2019-01-25 19:39 UTC, aperdomob commented on src/page/sign-in-step.page.ts
> +  public async signIn(): Promise<void> {
que reciba los dos parametros de email y password

2019-01-27 20:25 UTC, Juansereina commented on src/page/sign-in-step.page.ts
> +  public async signIn(): Promise<void> {
done

2019-02-21 13:17 UTC, aperdomob approved these changes

2019-05-29 20:57 UTC, merged