Exercise step 7
Juansereina/protractor-workshop-2019 pull request #7
Opened 2019-01-16 22:10 UTC by Juansereina

2019-01-16 23:37 UTC, aperdomob requested changes

2019-01-16 23:37 UTC, aperdomob commented on package.json
> +    "tslint": "^5.12.1",
agregalas como dev-dependecies

2019-01-17 13:32 UTC, Juansereina commented on package.json
> +    "tslint": "^5.12.1",
Listo!

2019-01-17 15:10 UTC, aperdomob approved these changes

2019-01-17 15:10 UTC, merged